### ISSUE TITLE
Cannot find module 'react'

### ISSUE THREAD

**Issue by ar1a** [emacs-lsp/lsp-javascript#19]
Hi! I have this issue in my jsx files where it appears to be broken.
![image](https://user-images.githubusercontent.com/8436007/41189176-05a6f9ba-6c0d-11e8-925a-9a1827cfc384.png)
The source files are here: https://github.com/ar1a/Tungsten-client
My config is here https://github.com/ar1a/dotfiles/blob/f78cbc43fc039e6aa86b06c6846f48df2d6b093b/emacs/.doom.d/modules/completion/lsp/config.el#L33

**Comment by gpittarelli** [comment]
Hi, thanks for the report.

I think this is a config issue in your project; for comparison, VS Code also shows the same issues. It can't find react or react-router-dom because those libraries need type declarations installed via `npm i @types/react @types/react-router-dom` (and so on for other dependencies). `react-md` ships with TS declarations, but only for a direct `import from 'react-md'`; that library doesn't support type-checking when you import a specific path like that.

An easier solution would be to remove `checkJS: true` from jsconfig.json. I tested it and this yields the much more reasonable behavior of providing nice autocomplete and type information on-hover, without complaining about all the library issues.

**Comment by ar1a** [comment]
Thanks!
